begin;

-- Fix: when deleting a HH lançamento (public.hh_lancamentos), also delete the linked
-- apontamento(s) in public.apontamentos_horas.
--
-- Some bases do not have a soft-delete column in apontamentos_horas, so we must hard-delete.
-- The FK ON DELETE CASCADE should cover it when hh_lancamento_id is present, but this trigger
-- also cleans up any orphan rows generated by HH (gerado_por_hh=true) that might not be linked.

create or replace function public.fn_hh_delete_apontamento() returns trigger
language plpgsql
security definer
set search_path = public
set row_security = off
as $$
begin
  -- Primary: delete by hh_lancamento_id
  delete from public.apontamentos_horas ah
  where ah.hh_lancamento_id = old.id;

  -- Fallback: delete orphan apontamentos generated by HH (if any)
  delete from public.apontamentos_horas ah
  where ah.hh_lancamento_id is null
    and ah.tenant_id = old.tenant_id
    and ah.empresa_id = old.empresa_id
    and ah.os_id = old.os_id::int
    and ah.colaborador_id = old.colaborador_id
    and ah.data = old.data
    and ah.gerado_por_hh = true;

  return old;
end;
$$;

commit;

