begin;

set local lock_timeout = '5s';
set local statement_timeout = '120s';

create table if not exists public.item_grupos (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  empresa_id uuid not null,
  codigo text not null,
  nome text not null,
  descricao text,
  grupo_pai_id bigint,
  ativo boolean not null default true,
  criado_em timestamp without time zone not null default now(),
  criado_por text,
  atualizado_em timestamp without time zone not null default now(),
  atualizado_por text,
  constraint item_grupos_codigo_formato_check check (codigo = upper(codigo) and codigo ~ '^[A-Z0-9_]+$'),
  constraint item_grupos_nome_nao_vazio_check check (btrim(nome) <> ''),
  constraint item_grupos_tenant_empresa_codigo_key unique (tenant_id, empresa_id, codigo),
  constraint item_grupos_tenant_empresa_id_key unique (tenant_id, empresa_id, id),
  constraint item_grupos_pai_mesmo_escopo_fk
    foreign key (tenant_id, empresa_id, grupo_pai_id)
    references public.item_grupos (tenant_id, empresa_id, id)
    on delete restrict,
  constraint item_grupos_pai_diferente_check check (grupo_pai_id is null or grupo_pai_id <> id)
);

create index if not exists idx_item_grupos_tenant_empresa_pai
  on public.item_grupos (tenant_id, empresa_id, grupo_pai_id, nome)
  where ativo;

alter table public.itens
  add column if not exists grupo_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'itens_grupo_mesmo_escopo_fk'
      and conrelid = 'public.itens'::regclass
  ) then
    alter table public.itens
      add constraint itens_grupo_mesmo_escopo_fk
      foreign key (tenant_id, empresa_id, grupo_id)
      references public.item_grupos (tenant_id, empresa_id, id)
      on delete restrict;
  end if;
end;
$$;

create index if not exists idx_itens_tenant_empresa_grupo
  on public.itens (tenant_id, empresa_id, grupo_id)
  where grupo_id is not null;

do $$
begin
  if to_regprocedure('public.set_updated_at()') is not null then
    drop trigger if exists trg_item_grupos_atualizado_em on public.item_grupos;
    create trigger trg_item_grupos_atualizado_em
      before update on public.item_grupos
      for each row execute function public.set_updated_at();
  end if;
end;
$$;

alter table public.item_grupos enable row level security;

drop policy if exists item_grupos_select on public.item_grupos;
create policy item_grupos_select
  on public.item_grupos
  for select to authenticated
  using (
    tenant_id = public.current_tenant_id()
    and empresa_id = public.current_empresa_id()
    and (
      public.can('estoque', 'read')
      or public.can('os', 'read')
      or public.can('cad_itens', 'write')
    )
  );

drop policy if exists item_grupos_insert on public.item_grupos;
create policy item_grupos_insert
  on public.item_grupos
  for insert to authenticated
  with check (
    tenant_id = public.current_tenant_id()
    and empresa_id = public.current_empresa_id()
    and (public.can('cad_itens', 'write') or public.can('estoque', 'write'))
  );

drop policy if exists item_grupos_update on public.item_grupos;
create policy item_grupos_update
  on public.item_grupos
  for update to authenticated
  using (
    tenant_id = public.current_tenant_id()
    and empresa_id = public.current_empresa_id()
    and (public.can('cad_itens', 'write') or public.can('estoque', 'write'))
  )
  with check (
    tenant_id = public.current_tenant_id()
    and empresa_id = public.current_empresa_id()
    and (public.can('cad_itens', 'write') or public.can('estoque', 'write'))
  );

drop policy if exists item_grupos_delete on public.item_grupos;
create policy item_grupos_delete
  on public.item_grupos
  for delete to authenticated
  using (
    tenant_id = public.current_tenant_id()
    and empresa_id = public.current_empresa_id()
    and public.can('cad_itens', 'write')
  );

grant select, insert, update, delete on public.item_grupos to authenticated;
grant usage, select on sequence public.item_grupos_id_seq to authenticated;

comment on table public.item_grupos is
  'Taxonomia controlada de grupos de itens, isolada por tenant e empresa para classificacao e normalizacao de cadastros.';
comment on column public.itens.grupo_id is
  'Grupo controlado do item. Mantem categoria e subcategoria legadas sem alteracao.';

commit;
