begin;

set local lock_timeout = '10s';
set local statement_timeout = '180s';

-- Grupo economico: somente CNPJ possui raiz de oito digitos. CPF permanece
-- inteiro para evitar agrupamentos acidentais entre pessoas fisicas.
alter table public.clientes
  add column if not exists documento_raiz text
  generated always as (
    case
      when length(public.normalize_doc(documento)) = 14
        then left(public.normalize_doc(documento), 8)
      else null
    end
  ) stored;

create index if not exists idx_clientes_tenant_empresa_documento_raiz
  on public.clientes (tenant_id, empresa_id, documento_raiz)
  where documento_raiz is not null;

create or replace function public.cnpj_valido(p_documento text)
returns boolean
language plpgsql
immutable
strict
set search_path = pg_catalog
as $$
declare
  v text := regexp_replace(p_documento, '[^0-9]', '', 'g');
  v_soma integer := 0;
  v_resto integer;
  v_d1 integer;
  v_d2 integer;
  v_pesos1 integer[] := array[5,4,3,2,9,8,7,6,5,4,3,2];
  v_pesos2 integer[] := array[6,5,4,3,2,9,8,7,6,5,4,3,2];
  i integer;
begin
  if length(v) <> 14 or v ~ '^(.)\1{13}$' then
    return false;
  end if;

  for i in 1..12 loop
    v_soma := v_soma + substr(v, i, 1)::integer * v_pesos1[i];
  end loop;
  v_resto := v_soma % 11;
  v_d1 := case when v_resto < 2 then 0 else 11 - v_resto end;

  v_soma := 0;
  for i in 1..13 loop
    v_soma := v_soma + substr(v, i, 1)::integer * v_pesos2[i];
  end loop;
  v_resto := v_soma % 11;
  v_d2 := case when v_resto < 2 then 0 else 11 - v_resto end;

  return v_d1 = substr(v, 13, 1)::integer
     and v_d2 = substr(v, 14, 1)::integer;
end;
$$;

revoke all on function public.cnpj_valido(text) from public, anon;
grant execute on function public.cnpj_valido(text) to authenticated, service_role;

create table if not exists public.cliente_unidades (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  empresa_id uuid not null default public.current_empresa_id(),
  cliente_id integer not null,
  nome text not null,
  codigo text,
  documento varchar(20),
  cidade varchar(120),
  uf varchar(2),
  contato_nome text,
  contato_email text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid default a.fn_current_usuario_id(),
  updated_by uuid,
  constraint cliente_unidades_nome_nao_vazio_ck check (btrim(nome) <> ''),
  constraint cliente_unidades_uf_ck check (uf is null or uf ~ '^[A-Z]{2}$'),
  constraint cliente_unidades_cliente_fk
    foreign key (tenant_id, empresa_id, cliente_id)
    references public.clientes (tenant_id, empresa_id, id)
    on delete cascade
);

create unique index if not exists cliente_unidades_tenant_empresa_id_ux
  on public.cliente_unidades (tenant_id, empresa_id, id);

create unique index if not exists cliente_unidades_nome_ux
  on public.cliente_unidades (tenant_id, empresa_id, cliente_id, upper(btrim(nome)));

create index if not exists cliente_unidades_cliente_idx
  on public.cliente_unidades (tenant_id, empresa_id, cliente_id, ativo);

alter table public.cliente_unidades enable row level security;

drop policy if exists cliente_unidades_select on public.cliente_unidades;
create policy cliente_unidades_select
on public.cliente_unidades for select to authenticated
using (
  tenant_id = public.current_tenant_id()
  and empresa_id = public.current_empresa_id()
  and public.has_active_empresa_access(tenant_id, empresa_id)
);

drop policy if exists cliente_unidades_write on public.cliente_unidades;
create policy cliente_unidades_write
on public.cliente_unidades for all to authenticated
using (
  tenant_id = public.current_tenant_id()
  and empresa_id = public.current_empresa_id()
  and public.has_active_empresa_access(tenant_id, empresa_id)
  and (
    public.can('cad_clientes', 'write')
    or a.fn_current_empresa_papel(tenant_id, empresa_id) in ('ADMIN','DIRETOR','COORDENACAO','FINANCEIRO')
  )
)
with check (
  tenant_id = public.current_tenant_id()
  and empresa_id = public.current_empresa_id()
  and public.has_active_empresa_access(tenant_id, empresa_id)
  and (
    public.can('cad_clientes', 'write')
    or a.fn_current_empresa_papel(tenant_id, empresa_id) in ('ADMIN','DIRETOR','COORDENACAO','FINANCEIRO')
  )
);

grant select, insert, update, delete on public.cliente_unidades to authenticated;
grant all on public.cliente_unidades to service_role;
grant usage, select on sequence public.cliente_unidades_id_seq to authenticated, service_role;

alter table public.ordens_servico
  add column if not exists unidade_id bigint;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'ordens_servico_unidade_tenant_empresa_fk'
      and conrelid = 'public.ordens_servico'::regclass
  ) then
    alter table public.ordens_servico
      add constraint ordens_servico_unidade_tenant_empresa_fk
      foreign key (tenant_id, empresa_id, unidade_id)
      references public.cliente_unidades (tenant_id, empresa_id, id)
      on delete set null;
  end if;
end;
$$;

create index if not exists ordens_servico_unidade_idx
  on public.ordens_servico (tenant_id, empresa_id, unidade_id)
  where unidade_id is not null;

-- Cadastro inicial das seis fabricas da Portobello/PBG. Os nomes sao
-- editaveis e a unidade continua opcional em todas as OS.
insert into public.cliente_unidades (
  tenant_id, empresa_id, cliente_id, nome, codigo, cidade, uf
)
select c.tenant_id, c.empresa_id, c.id,
       'Fábrica ' || n.numero || ' — Tijucas',
       'FAB' || n.numero,
       'TIJUCAS', 'SC'
from public.clientes c
cross join (values (1),(2),(3),(4),(5),(6)) as n(numero)
where c.id = 1
  and c.documento_norm = '83475913000272'
on conflict do nothing;

-- Saneamento confirmado por referencias e documento. Todas as atualizacoes
-- sao limitadas ao tenant/empresa da Segau e sao idempotentes.
do $$
declare
  v_tenant constant uuid := '3ced7cfa-efbb-4f0f-addc-2028f60d1ca7';
  v_empresa constant uuid := 'f0e74f49-a127-46b4-901b-f7b37e43c690';
  v_vizinho_id integer;
begin
  -- origem -> destino: Cremer typo, Uniplast DV, Riosulense e CISER minimos.
  update public.ordens_servico os
     set cliente_id = m.destino,
         cliente_nome = d.nome
    from (values (96,178),(107,89),(85,14),(101,105)) as m(origem,destino)
    join public.clientes d on d.id = m.destino
   where os.tenant_id = v_tenant and os.empresa_id = v_empresa
     and os.cliente_id = m.origem
     and d.tenant_id = v_tenant and d.empresa_id = v_empresa;

  update m.orcamento o set cliente_id = m.destino
    from (values (96,178),(107,89),(85,14),(101,105)) as m(origem,destino)
   where o.tenant_id = v_tenant and o.empresa_id = v_empresa and o.cliente_id = m.origem;

  update f.documento_fiscal d set cliente_id = m.destino
    from (values (96,178),(107,89),(85,14),(101,105)) as m(origem,destino)
   where d.tenant_id = v_tenant and d.empresa_id = v_empresa and d.cliente_id = m.origem;

  update f.titulo t set cliente_id = m.destino
    from (values (96,178),(107,89),(85,14),(101,105)) as m(origem,destino)
   where t.tenant_id = v_tenant and t.empresa_id = v_empresa and t.cliente_id = m.origem;

  update public.cliente_contatos c set cliente_id = m.destino
    from (values (96,178),(107,89),(85,14),(101,105)) as m(origem,destino)
   where c.tenant_id = v_tenant and c.empresa_id = v_empresa and c.cliente_id = m.origem;

  update public.clientes c
     set ativo = false,
         observacoes = concat_ws(E'\n', nullif(btrim(c.observacoes), ''),
           'Cadastro mesclado no cliente ' || m.destino || ' pela migration Venda a Crédito em 29/08/2026.'),
         atualizado_em = now()
    from (values (96,178),(107,89),(85,14),(101,105)) as m(origem,destino)
   where c.tenant_id = v_tenant and c.empresa_id = v_empresa and c.id = m.origem;

  -- O projeto Rio Mathias identifica a Azimute Engenheiros Consultores.
  update public.clientes
     set documento = '04.967.284/0001-40',
         razao_social = coalesce(razao_social, 'AZIMUTE ENGENHEIROS CONSULTORES LTDA'),
         atualizado_em = now()
   where tenant_id = v_tenant and empresa_id = v_empresa and id = 199
     and nullif(public.normalize_doc(documento), '') is null;

  -- Reconciliacao das OS historicas sem cliente. Segau e identificada como
  -- cliente interno; todas ja estao faturadas e nao geram nova exposicao.
  update public.ordens_servico set cliente_id = 94 where tenant_id=v_tenant and empresa_id=v_empresa and id=8 and cliente_id is null;
  update public.ordens_servico set cliente_id = 31 where tenant_id=v_tenant and empresa_id=v_empresa and id=9 and cliente_id is null;
  update public.ordens_servico set cliente_id = 178 where tenant_id=v_tenant and empresa_id=v_empresa and id in (11,12,13,14) and cliente_id is null;
  update public.ordens_servico set cliente_id = 2 where tenant_id=v_tenant and empresa_id=v_empresa and id=22 and cliente_id is null;
  update public.ordens_servico set cliente_id = 42 where tenant_id=v_tenant and empresa_id=v_empresa and id between 25 and 36 and cliente_id is null;
  update public.ordens_servico set cliente_id = 77 where tenant_id=v_tenant and empresa_id=v_empresa and id in (37,38,39,40,54) and cliente_id is null;
  update public.ordens_servico set cliente_id = 43 where tenant_id=v_tenant and empresa_id=v_empresa and id=42 and cliente_id is null;
  update public.ordens_servico set cliente_id = 204 where tenant_id=v_tenant and empresa_id=v_empresa and id=49 and cliente_id is null;
  update public.ordens_servico set cliente_id = 39 where tenant_id=v_tenant and empresa_id=v_empresa and id in (70,82) and cliente_id is null;
  update public.ordens_servico set cliente_id = 314 where tenant_id=v_tenant and empresa_id=v_empresa and id in (73,74) and cliente_id is null;
  update public.ordens_servico set cliente_id = 83 where tenant_id=v_tenant and empresa_id=v_empresa and id=97 and cliente_id is null;

  -- "Vizinho" nao possui correspondencia segura. Preserva-se a identidade
  -- historica em um cadastro inativo, sem inventar CNPJ de terceiro.
  select id into v_vizinho_id
  from public.clientes
  where tenant_id=v_tenant and empresa_id=v_empresa and nome='VIZINHO (HISTÓRICO)'
  limit 1;

  if v_vizinho_id is null then
    insert into public.clientes (tenant_id, empresa_id, nome, razao_social, ativo, observacoes)
    values (v_tenant, v_empresa, 'VIZINHO (HISTÓRICO)', 'VIZINHO (HISTÓRICO)', false,
            'Criado para classificar a OS 50 faturada. CNPJ não identificado; não usar em novas OS.')
    returning id into v_vizinho_id;
  end if;

  update public.ordens_servico
     set cliente_id = v_vizinho_id
   where tenant_id=v_tenant and empresa_id=v_empresa and id=50 and cliente_id is null;
end;
$$;

create or replace view r.r_clientes_documento_pendencia
with (security_invoker = true)
as
select
  c.tenant_id,
  c.empresa_id,
  c.id as cliente_id,
  c.nome as cliente_nome,
  c.documento,
  c.documento_norm,
  c.ativo,
  case
    when nullif(c.documento_norm, '') is null then 'SEM_DOCUMENTO'
    when length(c.documento_norm) = 14 and not public.cnpj_valido(c.documento_norm) then 'CNPJ_INVALIDO'
    else null
  end as pendencia
from public.clientes c
where c.ativo = true
  and (
    nullif(c.documento_norm, '') is null
    or (length(c.documento_norm) = 14 and not public.cnpj_valido(c.documento_norm))
  );

grant select on r.r_clientes_documento_pendencia to authenticated;

notify pgrst, 'reload schema';

commit;
