-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20240102_fiscal.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
