-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20260221114500_fix_compra_varredura_itens_sem_deleted_at_e_baixa_os.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
