-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20260227_reset_apontamentos_horas_policies_members_only.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
