-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20260526193000_fix_import_nf_entrada_item_code_and_direct_os_validation.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
