-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20260305235900_fix_nfse_piscofins_debito_import_manual_backfill_jan_fev.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
