-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20260131_ap_manual_e_recorrencias.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
