-- Tarefas: agenda de colaborador com reserva de dia, no ERP web, no app e no
-- tablet compartilhado.
--
-- Uma tarefa amarra um colaborador a uma OS com uma descricao. Ela e "agendada"
-- (tem data e reserva o dia inteiro do colaborador) ou "sem data" (fica
-- pendente, sem reservar nada). Tarefa e apontamento sao independentes: concluir
-- uma tarefa nao gera hora nenhuma.
--
-- A regra central — um colaborador agendado num dia nao pode ser agendado de
-- novo naquele dia, por ninguem, em nenhuma outra OS — mora no banco, e nao na
-- tela: tarefas_reservas guarda uma linha por reserva, e o indice unico parcial
-- (colaborador_id, data) enquanto a reserva esta ativa e quem garante a
-- exclusividade mesmo com dois pedidos ao mesmo tempo. O mesmo vale por usuario
-- (colaboradores.user_id) para a mesma pessoa nao ser reservada por duas
-- empresas. Toda operacao que mexe na reserva (reagendar, trocar colaborador,
-- passar para sem data, cancelar, liberar) fica registrada na propria linha da
-- reserva (quem liberou, quando e por que) e no audit_log.
--
-- Concluir registra a execucao e NAO libera a reserva: o dia foi usado. Liberar
-- o dia de uma tarefa concluida e acao explicita da gestao (app_tarefas_liberar_reserva).
--
-- Quem pode o que (mesma hierarquia de fn_usuario_pode_alterar_apontamento):
--   - ADMIN, DIRETOR e COORDENACAO da empresa: criam e administram qualquer tarefa;
--   - responsavel da OS (ordens_servico.responsavel_aprovacao_id): cria e
--     administra as tarefas das OS dele;
--   - colaborador comum: ve as proprias tarefas e conclui as proprias pendentes.
-- Tudo validado no servidor, isolado por tenant e empresa. A conta do tablet
-- (APONTADOR autorizado em tablet_dispositivos) nao entra nas app_tarefas_*: ela
-- so enxerga as tarefas do colaborador identificado pelo PIN, via
-- app_tablet_tarefas / app_tablet_tarefa_concluir, e nunca aprova nem administra.
--
-- Idempotencia: criar e concluir aceitam uma chave (uuid gerada pela interface);
-- repetir a chave devolve o mesmo resultado sem gravar de novo. Concluir tambem
-- e idempotente pelo estado: concluir o que ja esta concluido devolve sucesso
-- com repetido = true.

begin;

set local lock_timeout = '5s';
set local statement_timeout = '120s';

-- Todas as funcoes do banco pertencem a postgres.
set local role postgres;

-- 1. Tabelas -------------------------------------------------------------------

create table if not exists public.tarefas (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null,
  empresa_id uuid not null,
  os_id integer not null references public.ordens_servico (id),
  colaborador_id uuid not null references public.colaboradores (id),
  tipo text not null,
  data date,
  descricao text not null,
  situacao text not null default 'pendente',
  criado_em timestamptz not null default now(),
  criado_por_user_id uuid,
  atualizado_em timestamptz not null default now(),
  atualizado_por_user_id uuid,
  concluida_em timestamptz,
  concluida_por_user_id uuid,
  concluida_por_sessao_id uuid references public.tablet_sessoes (id),
  cancelada_em timestamptz,
  cancelada_por_user_id uuid,
  cancelamento_motivo text,
  constraint chk_tarefas_tipo check (tipo in ('agendada', 'sem_data')),
  constraint chk_tarefas_situacao check (situacao in ('pendente', 'concluida', 'cancelada')),
  constraint chk_tarefas_data_por_tipo check ((tipo = 'agendada') = (data is not null)),
  constraint chk_tarefas_descricao check (char_length(btrim(descricao)) between 1 and 2000),
  constraint chk_tarefas_conclusao check ((situacao = 'concluida') = (concluida_em is not null)),
  constraint chk_tarefas_cancelamento check ((situacao = 'cancelada') = (cancelada_em is not null))
);

comment on table public.tarefas is
  'Tarefa de um colaborador numa OS. Agendada reserva o dia inteiro do colaborador (ver tarefas_reservas); sem data so fica pendente. Nao gera horas.';
comment on column public.tarefas.concluida_por_sessao_id is
  'Quando preenchido, a conclusao veio do tablet compartilhado nesta sessao de PIN (concluida_por_user_id e a conta do tablet).';

create index if not exists idx_tarefas_empresa_situacao_data
  on public.tarefas (tenant_id, empresa_id, situacao, data);
create index if not exists idx_tarefas_colaborador_data
  on public.tarefas (colaborador_id, data);
create index if not exists idx_tarefas_os
  on public.tarefas (os_id);

create table if not exists public.tarefas_reservas (
  id uuid primary key default gen_random_uuid(),
  -- Ordem de criacao dentro da tarefa: duas reservas da mesma transacao tem o
  -- mesmo criado_em, e o historico precisa saber qual veio depois.
  ordem bigint generated by default as identity,
  tenant_id uuid not null,
  empresa_id uuid not null,
  tarefa_id uuid not null references public.tarefas (id),
  colaborador_id uuid not null references public.colaboradores (id),
  usuario_id uuid,
  data date not null,
  criado_em timestamptz not null default now(),
  criado_por_user_id uuid,
  liberada_em timestamptz,
  liberada_por_user_id uuid,
  liberacao_motivo text
);

comment on table public.tarefas_reservas is
  'Reserva do dia inteiro de um colaborador por uma tarefa agendada. Uma linha por reserva; liberar preenche liberada_em (a linha fica como historico). Os indices unicos parciais garantem um colaborador (e um usuario) por dia.';

-- A exclusividade de verdade: um colaborador por dia, um usuario por dia,
-- uma reserva ativa por tarefa.
create unique index if not exists uq_tarefas_reservas__colaborador_dia
  on public.tarefas_reservas (colaborador_id, data)
  where liberada_em is null;
create unique index if not exists uq_tarefas_reservas__usuario_dia
  on public.tarefas_reservas (usuario_id, data)
  where liberada_em is null and usuario_id is not null;
create unique index if not exists uq_tarefas_reservas__tarefa_ativa
  on public.tarefas_reservas (tarefa_id)
  where liberada_em is null;
create index if not exists idx_tarefas_reservas_empresa_data
  on public.tarefas_reservas (tenant_id, empresa_id, data)
  where liberada_em is null;
create index if not exists idx_tarefas_reservas_tarefa
  on public.tarefas_reservas (tarefa_id, ordem);

create table if not exists public.tarefas_operacoes (
  chave uuid primary key,
  tenant_id uuid not null,
  operacao text not null,
  tarefa_id uuid,
  resultado jsonb not null,
  criado_em timestamptz not null default now()
);

comment on table public.tarefas_operacoes is
  'Chave de idempotencia das operacoes de tarefa (criar, concluir): repetir a chave devolve o mesmo resultado em vez de gravar de novo.';

-- Mesma postura das tabelas do tablet: RLS ligada e sem policy, entao so as
-- funcoes SECURITY DEFINER (row_security off) enxergam as tabelas.
alter table public.tarefas enable row level security;
alter table public.tarefas_reservas enable row level security;
alter table public.tarefas_operacoes enable row level security;

revoke all on table public.tarefas from public, anon, authenticated;
revoke all on table public.tarefas_reservas from public, anon, authenticated;
revoke all on table public.tarefas_operacoes from public, anon, authenticated;

grant select, insert, update, delete, truncate, references, trigger
  on public.tarefas, public.tarefas_reservas, public.tarefas_operacoes
  to service_role;

-- Quem criou, alterou, concluiu, cancelou, reservou e liberou: audit_log.
drop trigger if exists trg_tarefas_audit on public.tarefas;
create trigger trg_tarefas_audit
after insert or update or delete on public.tarefas
for each row execute function public.audit_trigger();

drop trigger if exists trg_tarefas_reservas_audit on public.tarefas_reservas;
create trigger trg_tarefas_reservas_audit
after insert or update or delete on public.tarefas_reservas
for each row execute function public.audit_trigger();

-- Linha de tarefa como as telas veem: com nomes, situacao da reserva e o que a
-- pessoa logada pode fazer com ela. Tipo composto para as funcoes de lista e
-- de detalhe devolverem a mesma coisa.
do $tipo$
begin
  if not exists (select 1 from pg_type t join pg_namespace n on n.oid = t.typnamespace where n.nspname = 'public' and t.typname = 'tarefa_linha') then
    create type public.tarefa_linha as (
      id uuid,
      tipo text,
      data date,
      situacao text,
      colaborador_id uuid,
      colaborador_nome text,
      minha boolean,
      os_id integer,
      numero_os text,
      cliente_id integer,
      cliente_nome text,
      os_descricao text,
      os_status_fluxo text,
      -- Para a tela abrir a OS do jeito certo: a de HH lanca por horarios.
      os_usa_relatorio_hh boolean,
      os_responsavel_nome text,
      descricao text,
      criado_em timestamptz,
      criado_por_nome text,
      atualizado_em timestamptz,
      concluida_em timestamptz,
      concluida_por_nome text,
      concluida_pelo_tablet boolean,
      cancelada_em timestamptz,
      cancelada_por_nome text,
      cancelamento_motivo text,
      reserva_ativa boolean,
      reserva_liberada_em timestamptz,
      reserva_liberada_por_nome text,
      reserva_liberacao_motivo text,
      atrasada boolean,
      hoje boolean,
      pode_gerir boolean,
      pode_concluir boolean
    );
  end if;

  -- O tipo pode ter nascido numa versao anterior desta migration, sem os dois
  -- campos da OS. Sem isto, reaplicar o arquivo deixaria fn_tarefas_linhas com
  -- mais colunas do que o tipo tem.
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    join pg_attribute a on a.attrelid = t.typrelid
    where n.nspname = 'public'
      and t.typname = 'tarefa_linha'
      and a.attname = 'os_usa_relatorio_hh'
      and not a.attisdropped
  ) then
    alter type public.tarefa_linha add attribute os_usa_relatorio_hh boolean cascade;
    alter type public.tarefa_linha add attribute os_responsavel_nome text cascade;
  end if;
end;
$tipo$;

-- 2. Apoio (fn_*: so as RPCs chamam) ------------------------------------------------

create or replace function public.fn_tarefas_erro(p_tipo text, p_mensagem text)
returns jsonb
language sql
immutable
set search_path to 'pg_catalog'
as $$
  select jsonb_build_object(
    'sucesso', false,
    'erros', jsonb_build_array(jsonb_build_object('tipo', p_tipo, 'mensagem', p_mensagem)),
    'avisos', '[]'::jsonb
  );
$$;

-- Nome de quem fez: conta do ERP, perfil, colaborador vinculado ou o e-mail.
create or replace function public.fn_tarefas_nome_usuario(p_auth_uid uuid)
returns text
language sql
stable
security definer
set search_path to 'pg_catalog', 'public', 'a'
set row_security to 'off'
as $$
  select coalesce(
    (select nullif(btrim(usuario.nome), '') from a.usuario as usuario
      where usuario.auth_user_id = p_auth_uid and usuario.deleted_at is null
      order by usuario.ativo desc limit 1),
    (select nullif(btrim(perfil.nome), '') from public.profiles as perfil where perfil.id = p_auth_uid),
    (select nullif(btrim(colaborador.nome), '')::text from public.colaboradores as colaborador where colaborador.user_id = p_auth_uid limit 1),
    (select conta.email::text from auth.users as conta where conta.id = p_auth_uid)
  )
  where p_auth_uid is not null;
$$;

-- Quem esta chamando e o que pode. Levanta quando nao ha contexto de empresa ou
-- quando a conta e um tablet (o tablet tem as funcoes dele).
create or replace function public.fn_tarefas_contexto()
returns table (
  tenant_id uuid,
  empresa_id uuid,
  auth_uid uuid,
  papel text,
  colaborador_id uuid,
  gestao boolean,
  pode_criar boolean
)
language plpgsql
stable
security definer
set search_path to 'pg_catalog', 'public', 'a'
set row_security to 'off'
as $function$
declare
  v_auth_uid uuid := auth.uid();
  v_tenant_id uuid := public.current_tenant_id();
  v_empresa_id uuid := public.current_empresa_id();
  v_papel text;
  v_colaborador_id uuid;
  v_gestao boolean;
begin
  if v_auth_uid is null
     or v_tenant_id is null
     or v_empresa_id is null
     or not public.has_active_empresa_access(v_tenant_id, v_empresa_id) then
    raise exception 'Autenticação e contexto de empresa são obrigatórios.';
  end if;

  if (public.fn_tablet_dispositivo_atual()).id is not null then
    raise exception 'A conta do tablet não acessa tarefas pelo aplicativo. Identifique-se pelo PIN.';
  end if;

  v_papel := coalesce(a.fn_current_empresa_papel(v_tenant_id, v_empresa_id), '');

  select colaborador.id
    into v_colaborador_id
  from public.colaboradores as colaborador
  where colaborador.user_id = v_auth_uid
    and colaborador.tenant_id = v_tenant_id
    and colaborador.empresa_id = v_empresa_id
    and colaborador.ativo is true
  limit 1;

  v_gestao := v_papel in ('ADMIN', 'DIRETOR', 'COORDENACAO');

  return query
  select v_tenant_id, v_empresa_id, v_auth_uid, v_papel, v_colaborador_id, v_gestao,
         v_gestao or exists (
           select 1 from public.ordens_servico as os
           where os.tenant_id = v_tenant_id
             and os.empresa_id = v_empresa_id
             and os.responsavel_aprovacao_id = v_auth_uid
         );
end;
$function$;

-- Todas as tarefas que a pessoa pode ver, ja com nomes e permissoes.
create or replace function public.fn_tarefas_linhas(p_tenant_id uuid, p_empresa_id uuid, p_auth_uid uuid, p_gestao boolean, p_colaborador_id uuid)
returns setof public.tarefa_linha
language sql
stable
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $$
  with hoje as (select public.fn_tablet_data_hoje() as d)
  select
    t.id,
    t.tipo,
    t.data,
    t.situacao,
    t.colaborador_id,
    colab.nome::text,
    (p_colaborador_id is not null and t.colaborador_id = p_colaborador_id),
    t.os_id,
    coalesce(nullif(btrim(os.numero_os), ''), os.os_num::text, os.id::text),
    os.cliente_id,
    coalesce(nullif(btrim(os.cliente_nome), ''), nullif(btrim(cli.nome), ''), 'Cliente não informado')::text,
    os.descricao_servico,
    coalesce(nullif(lower(os.status_fluxo), ''), public.mapear_status_legado_para_fluxo(os.status)),
    coalesce(os.usa_relatorio_hh, false),
    public.fn_tarefas_nome_usuario(os.responsavel_aprovacao_id),
    t.descricao,
    t.criado_em,
    public.fn_tarefas_nome_usuario(t.criado_por_user_id),
    t.atualizado_em,
    t.concluida_em,
    case when t.concluida_por_sessao_id is not null then colab.nome::text || ' (pelo tablet)'
         else public.fn_tarefas_nome_usuario(t.concluida_por_user_id) end,
    t.concluida_por_sessao_id is not null,
    t.cancelada_em,
    public.fn_tarefas_nome_usuario(t.cancelada_por_user_id),
    t.cancelamento_motivo,
    reserva.id is not null,
    ultima.liberada_em,
    public.fn_tarefas_nome_usuario(ultima.liberada_por_user_id),
    ultima.liberacao_motivo,
    (t.situacao = 'pendente' and t.data is not null and t.data < hoje.d),
    (t.data is not null and t.data = hoje.d),
    (p_gestao or coalesce(os.responsavel_aprovacao_id = p_auth_uid, false)),
    (t.situacao = 'pendente' and (p_gestao or coalesce(os.responsavel_aprovacao_id = p_auth_uid, false)
       or (p_colaborador_id is not null and t.colaborador_id = p_colaborador_id)))
  from public.tarefas as t
  cross join hoje
  join public.ordens_servico as os on os.id = t.os_id
  join public.colaboradores as colab on colab.id = t.colaborador_id
  left join public.clientes as cli
    on cli.id = os.cliente_id and cli.tenant_id = t.tenant_id and cli.empresa_id = t.empresa_id
  left join public.tarefas_reservas as reserva
    on reserva.tarefa_id = t.id and reserva.liberada_em is null
  left join lateral (
    select r.liberada_em, r.liberada_por_user_id, r.liberacao_motivo
    from public.tarefas_reservas as r
    where r.tarefa_id = t.id and r.liberada_em is not null
    order by r.liberada_em desc, r.ordem desc
    limit 1
  ) as ultima on true
  where t.tenant_id = p_tenant_id
    and t.empresa_id = p_empresa_id
    and (p_gestao
         or coalesce(os.responsavel_aprovacao_id = p_auth_uid, false)
         or (p_colaborador_id is not null and t.colaborador_id = p_colaborador_id));
$$;

create or replace function public.fn_tarefas_linha_json(p_tarefa_id uuid, p_tenant_id uuid, p_empresa_id uuid, p_auth_uid uuid, p_gestao boolean, p_colaborador_id uuid)
returns jsonb
language sql
stable
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $$
  select to_jsonb(linha)
  from public.fn_tarefas_linhas(p_tenant_id, p_empresa_id, p_auth_uid, p_gestao, p_colaborador_id) as linha
  where linha.id = p_tarefa_id;
$$;

-- Ha outra reserva ativa para este colaborador (ou para a mesma pessoa em outra
-- empresa) nesta data? Devolve o erro pronto, com os detalhes so para quem pode
-- ver a tarefa que ocupa o dia; ou nulo se o dia esta livre.
create or replace function public.fn_tarefas_conflito(
  p_tenant_id uuid,
  p_empresa_id uuid,
  p_colaborador_id uuid,
  p_usuario_id uuid,
  p_data date,
  p_excluir_tarefa_id uuid,
  p_auth_uid uuid,
  p_gestao boolean,
  p_colaborador_proprio uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_conflito record;
  v_visivel boolean;
  v_detalhe jsonb;
begin
  select r.tarefa_id,
         r.colaborador_id,
         colab.nome as colaborador_nome,
         t.tenant_id,
         t.empresa_id,
         t.colaborador_id as tarefa_colaborador_id,
         t.descricao,
         t.situacao,
         os.responsavel_aprovacao_id,
         coalesce(nullif(btrim(os.numero_os), ''), os.os_num::text, os.id::text) as numero_os,
         coalesce(nullif(btrim(os.cliente_nome), ''), 'Cliente não informado') as cliente_nome
    into v_conflito
  from public.tarefas_reservas as r
  join public.tarefas as t on t.id = r.tarefa_id
  join public.ordens_servico as os on os.id = t.os_id
  join public.colaboradores as colab on colab.id = r.colaborador_id
  where r.liberada_em is null
    and r.data = p_data
    and (r.colaborador_id = p_colaborador_id
         or (p_usuario_id is not null and r.usuario_id = p_usuario_id))
    and (p_excluir_tarefa_id is null or r.tarefa_id <> p_excluir_tarefa_id)
  order by (r.colaborador_id = p_colaborador_id) desc
  limit 1;

  if not found then
    return null;
  end if;

  v_visivel := v_conflito.tenant_id = p_tenant_id
    and v_conflito.empresa_id = p_empresa_id
    and (p_gestao
         or coalesce(v_conflito.responsavel_aprovacao_id = p_auth_uid, false)
         or (p_colaborador_proprio is not null and v_conflito.tarefa_colaborador_id = p_colaborador_proprio));

  if v_visivel then
    v_detalhe := jsonb_build_object(
      'tarefa_id', v_conflito.tarefa_id,
      'numero_os', v_conflito.numero_os,
      'cliente_nome', v_conflito.cliente_nome,
      'descricao', v_conflito.descricao,
      'situacao', v_conflito.situacao
    );
  end if;

  return public.fn_tarefas_erro(
    'colaborador_reservado',
    format('%s já está reservado(a) em %s.', v_conflito.colaborador_nome, to_char(p_data, 'DD/MM/YYYY'))
  ) || jsonb_build_object('conflito', v_detalhe, 'data', p_data, 'colaborador_id', p_colaborador_id);
end;
$function$;

-- Reserva o dia para a tarefa. Chamar dentro de um bloco com tratamento de
-- SQLSTATE 'P0T01' (dia ocupado; detail traz o erro pronto em json) e de
-- unique_violation (dois pedidos ao mesmo tempo: o indice unico decide).
create or replace function public.fn_tarefas_reservar(
  p_tarefa public.tarefas,
  p_usuario_id uuid,
  p_data date,
  p_auth_uid uuid,
  p_gestao boolean,
  p_colaborador_proprio uuid
)
returns uuid
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_conflito jsonb;
  v_reserva_id uuid;
begin
  -- Serializa os pedidos do mesmo colaborador/dia (e da mesma pessoa/dia):
  -- o segundo espera o primeiro terminar e ja enxerga a reserva dele.
  perform pg_advisory_xact_lock(hashtextextended('tarefa-reserva:' || p_tarefa.colaborador_id::text || ':' || p_data::text, 0));
  if p_usuario_id is not null then
    perform pg_advisory_xact_lock(hashtextextended('tarefa-reserva-usuario:' || p_usuario_id::text || ':' || p_data::text, 0));
  end if;

  v_conflito := public.fn_tarefas_conflito(
    p_tarefa.tenant_id, p_tarefa.empresa_id, p_tarefa.colaborador_id, p_usuario_id, p_data,
    p_tarefa.id, p_auth_uid, p_gestao, p_colaborador_proprio
  );
  if v_conflito is not null then
    raise exception using errcode = 'P0T01', message = 'colaborador_reservado', detail = v_conflito::text;
  end if;

  insert into public.tarefas_reservas (tenant_id, empresa_id, tarefa_id, colaborador_id, usuario_id, data, criado_por_user_id)
  values (p_tarefa.tenant_id, p_tarefa.empresa_id, p_tarefa.id, p_tarefa.colaborador_id, p_usuario_id, p_data, p_auth_uid)
  returning id into v_reserva_id;

  return v_reserva_id;
end;
$function$;

-- Libera a reserva ativa da tarefa (fica como historico). Devolve quantas liberou.
create or replace function public.fn_tarefas_liberar(p_tarefa_id uuid, p_auth_uid uuid, p_motivo text)
returns integer
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_liberadas integer;
begin
  update public.tarefas_reservas
     set liberada_em = now(),
         liberada_por_user_id = p_auth_uid,
         liberacao_motivo = p_motivo
   where tarefa_id = p_tarefa_id
     and liberada_em is null;
  get diagnostics v_liberadas = row_count;
  return v_liberadas;
end;
$function$;

-- Le a tarefa com trava de linha (serializa duas operacoes na mesma tarefa).
-- Devolve nulo quando nao existe nesta empresa.
create or replace function public.fn_tarefas_travar(p_tarefa_id uuid, p_tenant_id uuid, p_empresa_id uuid)
returns public.tarefas
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_tarefa public.tarefas;
begin
  select tarefa.*
    into v_tarefa
  from public.tarefas as tarefa
  where tarefa.id = p_tarefa_id
    and tarefa.tenant_id = p_tenant_id
    and tarefa.empresa_id = p_empresa_id
  for update;
  if not found then
    return null;
  end if;
  return v_tarefa;
end;
$function$;

create or replace function public.fn_tarefas_pode_gerir_os(p_os_id integer, p_auth_uid uuid, p_gestao boolean)
returns boolean
language sql
stable
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $$
  select p_gestao or exists (
    select 1 from public.ordens_servico as os
    where os.id = p_os_id and coalesce(os.responsavel_aprovacao_id = p_auth_uid, false)
  );
$$;

-- 3. RPCs do app e do web (app_tarefas_*) --------------------------------------------

create or replace function public.app_tarefas_contexto()
returns jsonb
language plpgsql
stable
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
begin
  select * into v_ctx from public.fn_tarefas_contexto();
  return jsonb_build_object(
    'gestao', v_ctx.gestao,
    'pode_criar', v_ctx.pode_criar,
    'papel', v_ctx.papel,
    'colaborador_id', v_ctx.colaborador_id,
    'hoje', public.fn_tablet_data_hoje()
  );
end;
$function$;

create or replace function public.app_tarefas_criar(
  p_tipo text,
  p_colaborador_id uuid,
  p_os_id integer,
  p_descricao text,
  p_data date default null,
  p_chave uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
  v_os record;
  v_colab record;
  v_tarefa public.tarefas;
  v_resultado jsonb;
  v_tipo text := lower(btrim(coalesce(p_tipo, '')));
  v_descricao text := btrim(coalesce(p_descricao, ''));
  v_data date;
  v_detalhe text;
begin
  select * into v_ctx from public.fn_tarefas_contexto();

  if p_chave is not null then
    perform pg_advisory_xact_lock(hashtextextended('tarefa-op:' || p_chave::text, 0));
    select op.resultado into v_resultado
    from public.tarefas_operacoes as op
    where op.chave = p_chave and op.tenant_id = v_ctx.tenant_id;
    if found then
      return v_resultado || jsonb_build_object('repetido', true);
    end if;
  end if;

  if v_tipo not in ('agendada', 'sem_data') then
    return public.fn_tarefas_erro('tipo_invalido', 'Escolha o tipo da tarefa: agendada ou sem data.');
  end if;
  v_data := case when v_tipo = 'agendada' then p_data end;
  if v_tipo = 'agendada' and v_data is null then
    return public.fn_tarefas_erro('data_obrigatoria', 'Tarefa agendada precisa de uma data.');
  end if;
  if char_length(v_descricao) = 0 then
    return public.fn_tarefas_erro('descricao_obrigatoria', 'Descreva a tarefa.');
  end if;
  if char_length(v_descricao) > 2000 then
    return public.fn_tarefas_erro('descricao_longa', 'A descrição pode ter no máximo 2000 caracteres.');
  end if;

  select os.id,
         os.responsavel_aprovacao_id,
         coalesce(os.tipo_documento, 'OS') as tipo_documento,
         coalesce(nullif(lower(os.status_fluxo), ''), public.mapear_status_legado_para_fluxo(os.status)) as status_fluxo
    into v_os
  from public.ordens_servico as os
  where os.id = p_os_id
    and os.tenant_id = v_ctx.tenant_id
    and os.empresa_id = v_ctx.empresa_id;
  if not found then
    return public.fn_tarefas_erro('os_invalida', 'A OS informada não existe nesta empresa.');
  end if;
  if v_os.tipo_documento <> 'OS' then
    return public.fn_tarefas_erro('os_invalida', 'Este documento é uma venda (OV) e não recebe tarefas.');
  end if;
  if v_os.status_fluxo not in ('em_andamento', 'em_andamento_garantia') then
    return public.fn_tarefas_erro('os_encerrada', 'Esta OS não está em andamento. Tarefas só podem ser criadas em OS em andamento.');
  end if;
  if not (v_ctx.gestao or coalesce(v_os.responsavel_aprovacao_id = v_ctx.auth_uid, false)) then
    return public.fn_tarefas_erro('sem_permissao', 'Seu perfil não cria tarefas nesta OS. Fale com a coordenação ou com o responsável da OS.');
  end if;

  select colab.id, colab.nome, colab.user_id
    into v_colab
  from public.colaboradores as colab
  where colab.id = p_colaborador_id
    and colab.tenant_id = v_ctx.tenant_id
    and colab.empresa_id = v_ctx.empresa_id
    and colab.ativo is true;
  if not found then
    return public.fn_tarefas_erro('colaborador_invalido', 'Escolha um colaborador ativo desta empresa.');
  end if;

  begin
    insert into public.tarefas (tenant_id, empresa_id, os_id, colaborador_id, tipo, data, descricao, situacao, criado_por_user_id, atualizado_por_user_id)
    values (v_ctx.tenant_id, v_ctx.empresa_id, v_os.id, v_colab.id, v_tipo, v_data, v_descricao, 'pendente', v_ctx.auth_uid, v_ctx.auth_uid)
    returning * into v_tarefa;

    if v_tipo = 'agendada' then
      perform public.fn_tarefas_reservar(v_tarefa, v_colab.user_id, v_data, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id);
    end if;
  exception
    when sqlstate 'P0T01' then
      get stacked diagnostics v_detalhe = pg_exception_detail;
      return v_detalhe::jsonb;
    when unique_violation then
      return coalesce(
        public.fn_tarefas_conflito(v_ctx.tenant_id, v_ctx.empresa_id, v_colab.id, v_colab.user_id, v_data, null, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
        public.fn_tarefas_erro('colaborador_reservado', 'O colaborador já está reservado naquela data.')
      );
  end;

  v_resultado := jsonb_build_object(
    'sucesso', true,
    'tarefa', public.fn_tarefas_linha_json(v_tarefa.id, v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
    'avisos', '[]'::jsonb
  );

  if p_chave is not null then
    insert into public.tarefas_operacoes (chave, tenant_id, operacao, tarefa_id, resultado)
    values (p_chave, v_ctx.tenant_id, 'criar', v_tarefa.id, v_resultado)
    on conflict (chave) do nothing;
  end if;

  return v_resultado;
end;
$function$;

create or replace function public.app_tarefas_alterar(p_tarefa_id uuid, p_descricao text)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
  v_tarefa public.tarefas;
  v_descricao text := btrim(coalesce(p_descricao, ''));
begin
  select * into v_ctx from public.fn_tarefas_contexto();
  v_tarefa := public.fn_tarefas_travar(p_tarefa_id, v_ctx.tenant_id, v_ctx.empresa_id);
  if v_tarefa.id is null then
    return public.fn_tarefas_erro('tarefa_nao_encontrada', 'Tarefa não encontrada nesta empresa.');
  end if;
  if not public.fn_tarefas_pode_gerir_os(v_tarefa.os_id, v_ctx.auth_uid, v_ctx.gestao) then
    return public.fn_tarefas_erro('sem_permissao', 'Só a coordenação ou o responsável da OS altera a descrição da tarefa.');
  end if;
  if v_tarefa.situacao <> 'pendente' then
    return public.fn_tarefas_erro('tarefa_encerrada', 'Tarefa concluída ou cancelada não pode ser alterada.');
  end if;
  if char_length(v_descricao) = 0 then
    return public.fn_tarefas_erro('descricao_obrigatoria', 'Descreva a tarefa.');
  end if;
  if char_length(v_descricao) > 2000 then
    return public.fn_tarefas_erro('descricao_longa', 'A descrição pode ter no máximo 2000 caracteres.');
  end if;

  update public.tarefas
     set descricao = v_descricao,
         atualizado_em = now(),
         atualizado_por_user_id = v_ctx.auth_uid
   where id = v_tarefa.id;

  return jsonb_build_object(
    'sucesso', true,
    'tarefa', public.fn_tarefas_linha_json(v_tarefa.id, v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
    'avisos', '[]'::jsonb
  );
end;
$function$;

-- Reagendar: p_data nova = libera o dia antigo e reserva o novo numa operacao so
-- (se o novo dia esta ocupado, nada muda). p_data nula = vira "sem data" e
-- libera o dia. Tarefa sem data com p_data = vira agendada (precisa do dia livre).
create or replace function public.app_tarefas_reagendar(p_tarefa_id uuid, p_data date default null)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
  v_tarefa public.tarefas;
  v_usuario_id uuid;
  v_detalhe text;
  v_anterior jsonb;
begin
  select * into v_ctx from public.fn_tarefas_contexto();
  v_tarefa := public.fn_tarefas_travar(p_tarefa_id, v_ctx.tenant_id, v_ctx.empresa_id);
  if v_tarefa.id is null then
    return public.fn_tarefas_erro('tarefa_nao_encontrada', 'Tarefa não encontrada nesta empresa.');
  end if;
  if not public.fn_tarefas_pode_gerir_os(v_tarefa.os_id, v_ctx.auth_uid, v_ctx.gestao) then
    return public.fn_tarefas_erro('sem_permissao', 'Só a coordenação ou o responsável da OS reagenda tarefas.');
  end if;
  if v_tarefa.situacao <> 'pendente' then
    return public.fn_tarefas_erro('tarefa_encerrada', 'Tarefa concluída ou cancelada não pode ser reagendada.');
  end if;

  v_anterior := jsonb_build_object('tipo', v_tarefa.tipo, 'data', v_tarefa.data);

  if (p_data is null and v_tarefa.tipo = 'sem_data') or (p_data is not null and v_tarefa.data = p_data) then
    return jsonb_build_object(
      'sucesso', true,
      'repetido', true,
      'tarefa', public.fn_tarefas_linha_json(v_tarefa.id, v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
      'anterior', v_anterior,
      'avisos', '[]'::jsonb
    );
  end if;

  select colab.user_id into v_usuario_id from public.colaboradores as colab where colab.id = v_tarefa.colaborador_id;

  begin
    if p_data is null then
      update public.tarefas
         set tipo = 'sem_data', data = null, atualizado_em = now(), atualizado_por_user_id = v_ctx.auth_uid
       where id = v_tarefa.id
      returning * into v_tarefa;
      perform public.fn_tarefas_liberar(v_tarefa.id, v_ctx.auth_uid, 'passou_para_sem_data');
    else
      update public.tarefas
         set tipo = 'agendada', data = p_data, atualizado_em = now(), atualizado_por_user_id = v_ctx.auth_uid
       where id = v_tarefa.id
      returning * into v_tarefa;
      perform public.fn_tarefas_liberar(v_tarefa.id, v_ctx.auth_uid, 'reagendada');
      perform public.fn_tarefas_reservar(v_tarefa, v_usuario_id, p_data, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id);
    end if;
  exception
    when sqlstate 'P0T01' then
      get stacked diagnostics v_detalhe = pg_exception_detail;
      return v_detalhe::jsonb;
    when unique_violation then
      return coalesce(
        public.fn_tarefas_conflito(v_ctx.tenant_id, v_ctx.empresa_id, v_tarefa.colaborador_id, v_usuario_id, p_data, v_tarefa.id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
        public.fn_tarefas_erro('colaborador_reservado', 'O colaborador já está reservado naquela data.')
      );
  end;

  return jsonb_build_object(
    'sucesso', true,
    'tarefa', public.fn_tarefas_linha_json(v_tarefa.id, v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
    'anterior', v_anterior,
    'avisos', '[]'::jsonb
  );
end;
$function$;

create or replace function public.app_tarefas_trocar_colaborador(p_tarefa_id uuid, p_colaborador_id uuid)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
  v_tarefa public.tarefas;
  v_colab record;
  v_detalhe text;
  v_anterior jsonb;
begin
  select * into v_ctx from public.fn_tarefas_contexto();
  v_tarefa := public.fn_tarefas_travar(p_tarefa_id, v_ctx.tenant_id, v_ctx.empresa_id);
  if v_tarefa.id is null then
    return public.fn_tarefas_erro('tarefa_nao_encontrada', 'Tarefa não encontrada nesta empresa.');
  end if;
  if not public.fn_tarefas_pode_gerir_os(v_tarefa.os_id, v_ctx.auth_uid, v_ctx.gestao) then
    return public.fn_tarefas_erro('sem_permissao', 'Só a coordenação ou o responsável da OS troca o colaborador da tarefa.');
  end if;
  if v_tarefa.situacao <> 'pendente' then
    return public.fn_tarefas_erro('tarefa_encerrada', 'Tarefa concluída ou cancelada não pode mudar de colaborador.');
  end if;

  select colab.id, colab.nome, colab.user_id
    into v_colab
  from public.colaboradores as colab
  where colab.id = p_colaborador_id
    and colab.tenant_id = v_ctx.tenant_id
    and colab.empresa_id = v_ctx.empresa_id
    and colab.ativo is true;
  if not found then
    return public.fn_tarefas_erro('colaborador_invalido', 'Escolha um colaborador ativo desta empresa.');
  end if;

  v_anterior := jsonb_build_object('colaborador_id', v_tarefa.colaborador_id);

  if v_tarefa.colaborador_id = v_colab.id then
    return jsonb_build_object(
      'sucesso', true,
      'repetido', true,
      'tarefa', public.fn_tarefas_linha_json(v_tarefa.id, v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
      'anterior', v_anterior,
      'avisos', '[]'::jsonb
    );
  end if;

  begin
    update public.tarefas
       set colaborador_id = v_colab.id, atualizado_em = now(), atualizado_por_user_id = v_ctx.auth_uid
     where id = v_tarefa.id
    returning * into v_tarefa;

    if v_tarefa.tipo = 'agendada' then
      perform public.fn_tarefas_liberar(v_tarefa.id, v_ctx.auth_uid, 'troca_de_colaborador');
      perform public.fn_tarefas_reservar(v_tarefa, v_colab.user_id, v_tarefa.data, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id);
    end if;
  exception
    when sqlstate 'P0T01' then
      get stacked diagnostics v_detalhe = pg_exception_detail;
      return v_detalhe::jsonb;
    when unique_violation then
      return coalesce(
        public.fn_tarefas_conflito(v_ctx.tenant_id, v_ctx.empresa_id, v_colab.id, v_colab.user_id, v_tarefa.data, v_tarefa.id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
        public.fn_tarefas_erro('colaborador_reservado', 'O colaborador já está reservado naquela data.')
      );
  end;

  return jsonb_build_object(
    'sucesso', true,
    'tarefa', public.fn_tarefas_linha_json(v_tarefa.id, v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
    'anterior', v_anterior,
    'avisos', '[]'::jsonb
  );
end;
$function$;

create or replace function public.app_tarefas_cancelar(p_tarefa_id uuid, p_motivo text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
  v_tarefa public.tarefas;
begin
  select * into v_ctx from public.fn_tarefas_contexto();
  v_tarefa := public.fn_tarefas_travar(p_tarefa_id, v_ctx.tenant_id, v_ctx.empresa_id);
  if v_tarefa.id is null then
    return public.fn_tarefas_erro('tarefa_nao_encontrada', 'Tarefa não encontrada nesta empresa.');
  end if;
  if not public.fn_tarefas_pode_gerir_os(v_tarefa.os_id, v_ctx.auth_uid, v_ctx.gestao) then
    return public.fn_tarefas_erro('sem_permissao', 'Só a coordenação ou o responsável da OS cancela tarefas.');
  end if;
  if v_tarefa.situacao = 'cancelada' then
    return jsonb_build_object(
      'sucesso', true,
      'repetido', true,
      'tarefa', public.fn_tarefas_linha_json(v_tarefa.id, v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
      'avisos', '[]'::jsonb
    );
  end if;
  if v_tarefa.situacao = 'concluida' then
    return public.fn_tarefas_erro('tarefa_concluida', 'Tarefa concluída não pode ser cancelada. Se o dia precisa ser liberado, use "Liberar reserva".');
  end if;

  update public.tarefas
     set situacao = 'cancelada',
         cancelada_em = now(),
         cancelada_por_user_id = v_ctx.auth_uid,
         cancelamento_motivo = nullif(btrim(coalesce(p_motivo, '')), ''),
         atualizado_em = now(),
         atualizado_por_user_id = v_ctx.auth_uid
   where id = v_tarefa.id;

  perform public.fn_tarefas_liberar(v_tarefa.id, v_ctx.auth_uid, 'cancelada');

  return jsonb_build_object(
    'sucesso', true,
    'tarefa', public.fn_tarefas_linha_json(v_tarefa.id, v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
    'avisos', '[]'::jsonb
  );
end;
$function$;

-- Concluir registra a execucao e mantem a reserva. Idempotente pela chave e pelo estado.
create or replace function public.app_tarefas_concluir(p_tarefa_id uuid, p_chave uuid default null)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
  v_tarefa public.tarefas;
  v_resultado jsonb;
  v_pode boolean;
begin
  select * into v_ctx from public.fn_tarefas_contexto();

  if p_chave is not null then
    perform pg_advisory_xact_lock(hashtextextended('tarefa-op:' || p_chave::text, 0));
    select op.resultado into v_resultado
    from public.tarefas_operacoes as op
    where op.chave = p_chave and op.tenant_id = v_ctx.tenant_id;
    if found then
      return v_resultado || jsonb_build_object('repetido', true);
    end if;
  end if;

  v_tarefa := public.fn_tarefas_travar(p_tarefa_id, v_ctx.tenant_id, v_ctx.empresa_id);
  if v_tarefa.id is null then
    return public.fn_tarefas_erro('tarefa_nao_encontrada', 'Tarefa não encontrada nesta empresa.');
  end if;

  v_pode := public.fn_tarefas_pode_gerir_os(v_tarefa.os_id, v_ctx.auth_uid, v_ctx.gestao)
    or (v_ctx.colaborador_id is not null and v_tarefa.colaborador_id = v_ctx.colaborador_id);
  if not v_pode then
    -- Quem nao pode nem ver a tarefa nao fica sabendo que ela existe.
    return public.fn_tarefas_erro('tarefa_nao_encontrada', 'Tarefa não encontrada nesta empresa.');
  end if;

  if v_tarefa.situacao = 'concluida' then
    return jsonb_build_object(
      'sucesso', true,
      'repetido', true,
      'tarefa', public.fn_tarefas_linha_json(v_tarefa.id, v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
      'avisos', '[]'::jsonb
    );
  end if;
  if v_tarefa.situacao = 'cancelada' then
    return public.fn_tarefas_erro('tarefa_cancelada', 'Esta tarefa foi cancelada e não pode ser concluída.');
  end if;

  update public.tarefas
     set situacao = 'concluida',
         concluida_em = now(),
         concluida_por_user_id = v_ctx.auth_uid,
         concluida_por_sessao_id = null,
         atualizado_em = now(),
         atualizado_por_user_id = v_ctx.auth_uid
   where id = v_tarefa.id;

  v_resultado := jsonb_build_object(
    'sucesso', true,
    'tarefa', public.fn_tarefas_linha_json(v_tarefa.id, v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
    'avisos', '[]'::jsonb
  );

  if p_chave is not null then
    insert into public.tarefas_operacoes (chave, tenant_id, operacao, tarefa_id, resultado)
    values (p_chave, v_ctx.tenant_id, 'concluir', v_tarefa.id, v_resultado)
    on conflict (chave) do nothing;
  end if;

  return v_resultado;
end;
$function$;

-- Libera o dia de uma tarefa concluida. Acao explicita da gestao, com motivo.
create or replace function public.app_tarefas_liberar_reserva(p_tarefa_id uuid, p_motivo text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
  v_tarefa public.tarefas;
  v_liberadas integer;
begin
  select * into v_ctx from public.fn_tarefas_contexto();
  v_tarefa := public.fn_tarefas_travar(p_tarefa_id, v_ctx.tenant_id, v_ctx.empresa_id);
  if v_tarefa.id is null then
    return public.fn_tarefas_erro('tarefa_nao_encontrada', 'Tarefa não encontrada nesta empresa.');
  end if;
  if not public.fn_tarefas_pode_gerir_os(v_tarefa.os_id, v_ctx.auth_uid, v_ctx.gestao) then
    return public.fn_tarefas_erro('sem_permissao', 'Só a coordenação ou o responsável da OS libera a reserva de uma tarefa.');
  end if;
  if v_tarefa.situacao = 'pendente' then
    return public.fn_tarefas_erro('tarefa_pendente', 'Para liberar o dia de uma tarefa pendente, reagende-a ou passe-a para sem data.');
  end if;

  v_liberadas := public.fn_tarefas_liberar(v_tarefa.id, v_ctx.auth_uid, coalesce(nullif(btrim(coalesce(p_motivo, '')), ''), 'liberada_pela_gestao'));

  update public.tarefas
     set atualizado_em = now(), atualizado_por_user_id = v_ctx.auth_uid
   where id = v_tarefa.id;

  return jsonb_build_object(
    'sucesso', true,
    'repetido', v_liberadas = 0,
    'liberadas', v_liberadas,
    'tarefa', public.fn_tarefas_linha_json(v_tarefa.id, v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id),
    'avisos', '[]'::jsonb
  );
end;
$function$;

-- Listas: 'agendadas' (pendentes com data, atrasadas primeiro), 'sem_data'
-- (pendentes sem data), 'historico' (concluidas e canceladas) ou 'todas'.
create or replace function public.app_tarefas_listar(
  p_secao text default 'agendadas',
  p_de date default null,
  p_ate date default null,
  p_colaborador_id uuid default null,
  p_os_id integer default null,
  p_busca text default null
)
returns setof public.tarefa_linha
language plpgsql
stable
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
  v_secao text := lower(btrim(coalesce(p_secao, 'agendadas')));
  v_busca text := nullif(btrim(coalesce(p_busca, '')), '');
begin
  select * into v_ctx from public.fn_tarefas_contexto();

  if v_secao not in ('agendadas', 'sem_data', 'historico', 'todas') then
    raise exception 'Seção inválida: %', v_secao;
  end if;

  return query
  select linha.*
  from public.fn_tarefas_linhas(v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id) as linha
  where (v_secao <> 'agendadas' or (linha.situacao = 'pendente' and linha.tipo = 'agendada'))
    and (v_secao <> 'sem_data' or (linha.situacao = 'pendente' and linha.tipo = 'sem_data'))
    and (v_secao <> 'historico' or linha.situacao in ('concluida', 'cancelada'))
    and (p_colaborador_id is null or linha.colaborador_id = p_colaborador_id)
    and (p_os_id is null or linha.os_id = p_os_id)
    and (p_de is null or case
           when v_secao = 'historico' then (coalesce(linha.concluida_em, linha.cancelada_em) at time zone 'America/Sao_Paulo')::date >= p_de
           when v_secao = 'sem_data' then true
           else linha.data >= p_de end)
    and (p_ate is null or case
           when v_secao = 'historico' then (coalesce(linha.concluida_em, linha.cancelada_em) at time zone 'America/Sao_Paulo')::date <= p_ate
           when v_secao = 'sem_data' then true
           else linha.data <= p_ate end)
    and (v_busca is null
         or linha.descricao ilike '%' || v_busca || '%'
         or linha.numero_os ilike '%' || v_busca || '%'
         or linha.cliente_nome ilike '%' || v_busca || '%'
         or linha.colaborador_nome ilike '%' || v_busca || '%')
  order by
    case when v_secao = 'historico' then coalesce(linha.concluida_em, linha.cancelada_em) end desc nulls last,
    case when v_secao in ('agendadas', 'todas') then linha.data end asc nulls last,
    linha.colaborador_nome asc,
    linha.criado_em desc;
end;
$function$;

create or replace function public.app_tarefas_detalhe(p_tarefa_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
  v_tarefa jsonb;
  v_reservas jsonb;
begin
  select * into v_ctx from public.fn_tarefas_contexto();
  v_tarefa := public.fn_tarefas_linha_json(p_tarefa_id, v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id);
  if v_tarefa is null then
    return public.fn_tarefas_erro('tarefa_nao_encontrada', 'Tarefa não encontrada nesta empresa.');
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
           'id', r.id,
           'data', r.data,
           'colaborador_nome', colab.nome,
           'criado_em', r.criado_em,
           'criado_por_nome', public.fn_tarefas_nome_usuario(r.criado_por_user_id),
           'ativa', r.liberada_em is null,
           'liberada_em', r.liberada_em,
           'liberada_por_nome', public.fn_tarefas_nome_usuario(r.liberada_por_user_id),
           'liberacao_motivo', r.liberacao_motivo
         ) order by r.ordem), '[]'::jsonb)
    into v_reservas
  from public.tarefas_reservas as r
  join public.colaboradores as colab on colab.id = r.colaborador_id
  where r.tarefa_id = p_tarefa_id;

  return jsonb_build_object('sucesso', true, 'tarefa', v_tarefa, 'reservas', v_reservas);
end;
$function$;

-- Contadores para a aba: so o que a pessoa pode ver, cada tarefa contada uma vez.
create or replace function public.app_tarefas_contar()
returns jsonb
language plpgsql
stable
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
  v_resultado jsonb;
begin
  select * into v_ctx from public.fn_tarefas_contexto();

  select jsonb_build_object(
    'hoje', count(*) filter (where linha.situacao = 'pendente' and linha.hoje),
    'atrasadas', count(*) filter (where linha.atrasada),
    'futuras', count(*) filter (where linha.situacao = 'pendente' and linha.tipo = 'agendada' and not linha.hoje and not linha.atrasada),
    'agendadas', count(*) filter (where linha.situacao = 'pendente' and linha.tipo = 'agendada'),
    'sem_data', count(*) filter (where linha.situacao = 'pendente' and linha.tipo = 'sem_data'),
    'atencao', count(*) filter (where linha.situacao = 'pendente' and (linha.hoje or linha.atrasada)),
    'minhas_pendentes', count(*) filter (where linha.situacao = 'pendente' and linha.minha),
    'gestao', v_ctx.gestao,
    'pode_criar', v_ctx.pode_criar,
    'hoje_data', public.fn_tablet_data_hoje()
  )
    into v_resultado
  from public.fn_tarefas_linhas(v_ctx.tenant_id, v_ctx.empresa_id, v_ctx.auth_uid, v_ctx.gestao, v_ctx.colaborador_id) as linha;

  return v_resultado;
end;
$function$;

-- Agenda por data e colaborador: quem cria tarefas ve todos os dias ocupados da
-- empresa (o detalhe so das tarefas que pode ver); colaborador comum ve os dele.
create or replace function public.app_tarefas_agenda(p_de date, p_ate date)
returns table (
  data date,
  colaborador_id uuid,
  colaborador_nome text,
  tarefa_id uuid,
  situacao text,
  detalhe_visivel boolean,
  numero_os text,
  cliente_nome text,
  descricao text
)
language plpgsql
stable
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
begin
  select * into v_ctx from public.fn_tarefas_contexto();
  if p_de is null or p_ate is null or p_ate < p_de or p_ate - p_de > 92 then
    raise exception 'Informe um período de até 93 dias.';
  end if;

  return query
  select
    r.data,
    r.colaborador_id,
    colab.nome::text,
    r.tarefa_id,
    t.situacao,
    (v_ctx.gestao or coalesce(os.responsavel_aprovacao_id = v_ctx.auth_uid, false)
      or (v_ctx.colaborador_id is not null and t.colaborador_id = v_ctx.colaborador_id)) as detalhe_visivel,
    case when v_ctx.gestao or coalesce(os.responsavel_aprovacao_id = v_ctx.auth_uid, false)
           or (v_ctx.colaborador_id is not null and t.colaborador_id = v_ctx.colaborador_id)
         then coalesce(nullif(btrim(os.numero_os), ''), os.os_num::text, os.id::text) end,
    case when v_ctx.gestao or coalesce(os.responsavel_aprovacao_id = v_ctx.auth_uid, false)
           or (v_ctx.colaborador_id is not null and t.colaborador_id = v_ctx.colaborador_id)
         then coalesce(nullif(btrim(os.cliente_nome), ''), 'Cliente não informado')::text end,
    case when v_ctx.gestao or coalesce(os.responsavel_aprovacao_id = v_ctx.auth_uid, false)
           or (v_ctx.colaborador_id is not null and t.colaborador_id = v_ctx.colaborador_id)
         then t.descricao end
  from public.tarefas_reservas as r
  join public.tarefas as t on t.id = r.tarefa_id
  join public.ordens_servico as os on os.id = t.os_id
  join public.colaboradores as colab on colab.id = r.colaborador_id
  where r.liberada_em is null
    and r.tenant_id = v_ctx.tenant_id
    and r.empresa_id = v_ctx.empresa_id
    and r.data between p_de and p_ate
    and (v_ctx.pode_criar or (v_ctx.colaborador_id is not null and t.colaborador_id = v_ctx.colaborador_id))
  order by r.data, colab.nome;
end;
$function$;

-- Colaboradores ativos da empresa para escolher na tarefa, com o dia ocupado ou nao.
create or replace function public.app_tarefas_colaboradores(p_data date default null)
returns table (
  id uuid,
  nome text,
  cargo text,
  sou_eu boolean,
  ocupado boolean,
  ocupado_tarefa_id uuid,
  ocupado_resumo text
)
language plpgsql
stable
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
begin
  select * into v_ctx from public.fn_tarefas_contexto();
  if not v_ctx.pode_criar then
    raise exception 'Seu perfil não cria tarefas.';
  end if;

  return query
  select
    colab.id,
    colab.nome::text,
    colab.cargo::text,
    colab.user_id is not distinct from v_ctx.auth_uid,
    ocupacao.tarefa_id is not null,
    case when ocupacao.visivel then ocupacao.tarefa_id end,
    case when ocupacao.tarefa_id is null then null
         when ocupacao.visivel then ocupacao.resumo
         else 'Reservado(a) neste dia' end
  from public.colaboradores as colab
  left join lateral (
    select r.tarefa_id,
           (t.tenant_id = v_ctx.tenant_id and t.empresa_id = v_ctx.empresa_id
             and (v_ctx.gestao or coalesce(os.responsavel_aprovacao_id = v_ctx.auth_uid, false)
                  or (v_ctx.colaborador_id is not null and t.colaborador_id = v_ctx.colaborador_id))) as visivel,
           'OS ' || coalesce(nullif(btrim(os.numero_os), ''), os.os_num::text, os.id::text) || ' · '
             || coalesce(nullif(btrim(os.cliente_nome), ''), 'Cliente não informado') as resumo
    from public.tarefas_reservas as r
    join public.tarefas as t on t.id = r.tarefa_id
    join public.ordens_servico as os on os.id = t.os_id
    where p_data is not null
      and r.liberada_em is null
      and r.data = p_data
      and (r.colaborador_id = colab.id or (colab.user_id is not null and r.usuario_id = colab.user_id))
    order by (r.colaborador_id = colab.id) desc
    limit 1
  ) as ocupacao on true
  where colab.tenant_id = v_ctx.tenant_id
    and colab.empresa_id = v_ctx.empresa_id
    and colab.ativo is true
  order by colab.nome;
end;
$function$;

-- OS em andamento onde a pessoa pode criar tarefa, agrupavel por cliente.
-- Quem e gestao ve todas as OS em andamento pelas RPCs de sempre; quem so e
-- responsavel de OS usa esta, que ja vem filtrada.
-- O drop e porque a lista de colunas mudou (ganhou total_horas) e o Postgres nao
-- troca o tipo de retorno por "create or replace".
drop function if exists public.app_tarefas_os_elegiveis(text);
create or replace function public.app_tarefas_os_elegiveis(p_busca text default null)
returns table (
  id integer,
  numero_os text,
  os_num bigint,
  cliente_id integer,
  cliente_nome text,
  descricao_servico text,
  status_fluxo text,
  usa_relatorio_hh boolean,
  responsavel_nome text,
  total_horas numeric,
  tarefas_pendentes integer
)
language plpgsql
stable
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_ctx record;
  v_busca text := nullif(btrim(coalesce(p_busca, '')), '');
begin
  select * into v_ctx from public.fn_tarefas_contexto();

  return query
  select
    os.id,
    coalesce(nullif(btrim(os.numero_os), ''), os.os_num::text, os.id::text)::text,
    os.os_num,
    os.cliente_id,
    coalesce(nullif(btrim(os.cliente_nome), ''), nullif(btrim(cli.nome), ''), 'Cliente não informado')::text,
    os.descricao_servico,
    coalesce(nullif(lower(os.status_fluxo), ''), public.mapear_status_legado_para_fluxo(os.status))::text,
    coalesce(os.usa_relatorio_hh, false),
    public.fn_tarefas_nome_usuario(os.responsavel_aprovacao_id),
    -- Mesma conta de app_os_do_cliente, para o cartao da OS mostrar as horas de
    -- verdade tambem para quem so e responsavel de OS.
    coalesce((select sum(apontamento.horas) from public.apontamentos_horas as apontamento
               where apontamento.os_id = os.id
                 and apontamento.tenant_id = v_ctx.tenant_id
                 and apontamento.empresa_id = v_ctx.empresa_id), 0)::numeric,
    (select count(*)::integer from public.tarefas as t where t.os_id = os.id and t.situacao = 'pendente')
  from public.ordens_servico as os
  left join public.clientes as cli
    on cli.id = os.cliente_id and cli.tenant_id = v_ctx.tenant_id and cli.empresa_id = v_ctx.empresa_id
  where os.tenant_id = v_ctx.tenant_id
    and os.empresa_id = v_ctx.empresa_id
    and coalesce(os.tipo_documento, 'OS') = 'OS'
    and public.app_mobile_status_os_compativel(os.status_fluxo, os.status, array['em_andamento'])
    and (v_ctx.gestao or coalesce(os.responsavel_aprovacao_id = v_ctx.auth_uid, false))
    and (v_busca is null
         or os.numero_os ilike '%' || v_busca || '%'
         or os.os_num::text ilike '%' || v_busca || '%'
         or os.cliente_nome ilike '%' || v_busca || '%'
         or cli.nome ilike '%' || v_busca || '%'
         or os.descricao_servico ilike '%' || v_busca || '%')
  order by 5, os.data_abertura desc nulls last, os.id desc;
end;
$function$;

-- 4. Tablet compartilhado ------------------------------------------------------------

-- Tarefas do colaborador identificado pelo PIN: pendentes (agendadas e sem data)
-- e as que ele concluiu hoje. Nada de aprovacao nem de administracao.
create or replace function public.app_tablet_tarefas(p_sessao_token text)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_sessao public.tablet_sessoes;
  v_hoje date := public.fn_tablet_data_hoje();
  v_colaborador_nome text;
  v_agendadas jsonb;
  v_sem_data jsonb;
  v_concluidas_hoje jsonb;
begin
  v_sessao := public.fn_tablet_validar_sessao(p_sessao_token);
  if v_sessao.id is null then
    return public.fn_tablet_erro_sessao();
  end if;

  select colab.nome into v_colaborador_nome from public.colaboradores as colab where colab.id = v_sessao.colaborador_id;

  with tarefas_do_colaborador as (
    select t.id, t.tipo, t.data, t.situacao, t.descricao, t.concluida_em, t.criado_em,
           coalesce(nullif(btrim(os.numero_os), ''), os.os_num::text, os.id::text) as numero_os,
           coalesce(nullif(btrim(os.cliente_nome), ''), 'Cliente não informado') as cliente_nome,
           os.descricao_servico as os_descricao,
           (t.situacao = 'pendente' and t.data is not null and t.data < v_hoje) as atrasada,
           (t.data = v_hoje) as hoje
    from public.tarefas as t
    join public.ordens_servico as os on os.id = t.os_id
    where t.tenant_id = v_sessao.tenant_id
      and t.empresa_id = v_sessao.empresa_id
      and t.colaborador_id = v_sessao.colaborador_id
      and (t.situacao = 'pendente'
           or (t.situacao = 'concluida' and (t.concluida_em at time zone 'America/Sao_Paulo')::date = v_hoje))
  )
  select
    coalesce((select jsonb_agg(to_jsonb(x) order by x.data, x.criado_em) from tarefas_do_colaborador as x where x.situacao = 'pendente' and x.tipo = 'agendada'), '[]'::jsonb),
    coalesce((select jsonb_agg(to_jsonb(x) order by x.criado_em) from tarefas_do_colaborador as x where x.situacao = 'pendente' and x.tipo = 'sem_data'), '[]'::jsonb),
    coalesce((select jsonb_agg(to_jsonb(x) order by x.concluida_em desc) from tarefas_do_colaborador as x where x.situacao = 'concluida'), '[]'::jsonb)
    into v_agendadas, v_sem_data, v_concluidas_hoje;

  return jsonb_build_object(
    'sucesso', true,
    'colaborador_id', v_sessao.colaborador_id,
    'colaborador_nome', v_colaborador_nome,
    'hoje', v_hoje,
    'agendadas', v_agendadas,
    'sem_data', v_sem_data,
    'concluidas_hoje', v_concluidas_hoje
  );
end;
$function$;

create or replace function public.app_tablet_tarefa_concluir(p_sessao_token text, p_tarefa_id uuid, p_chave uuid default null)
returns jsonb
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
set row_security to 'off'
as $function$
declare
  v_sessao public.tablet_sessoes;
  v_tarefa public.tarefas;
  v_resultado jsonb;
  v_linha jsonb;
  v_ja_concluida boolean;
begin
  v_sessao := public.fn_tablet_validar_sessao(p_sessao_token);
  if v_sessao.id is null then
    return public.fn_tablet_erro_sessao();
  end if;

  if p_chave is not null then
    perform pg_advisory_xact_lock(hashtextextended('tarefa-op:' || p_chave::text, 0));
    select op.resultado into v_resultado
    from public.tarefas_operacoes as op
    where op.chave = p_chave and op.tenant_id = v_sessao.tenant_id;
    if found then
      return v_resultado || jsonb_build_object('repetido', true);
    end if;
  end if;

  v_tarefa := public.fn_tarefas_travar(p_tarefa_id, v_sessao.tenant_id, v_sessao.empresa_id);
  if v_tarefa.id is null or v_tarefa.colaborador_id <> v_sessao.colaborador_id then
    return public.fn_tablet_erro('tarefa_nao_encontrada', 'Esta tarefa não é sua ou não existe mais.');
  end if;
  if v_tarefa.situacao = 'cancelada' then
    return public.fn_tablet_erro('tarefa_cancelada', 'Esta tarefa foi cancelada e não pode ser concluída.');
  end if;

  -- Ja estava concluida: devolve sucesso sem gravar de novo.
  v_ja_concluida := v_tarefa.situacao = 'concluida';

  if not v_ja_concluida then
    update public.tarefas
       set situacao = 'concluida',
           concluida_em = now(),
           concluida_por_user_id = auth.uid(),
           concluida_por_sessao_id = v_sessao.id,
           atualizado_em = now(),
           atualizado_por_user_id = auth.uid()
     where id = v_tarefa.id
    returning * into v_tarefa;
  end if;

  select jsonb_build_object(
    'id', t.id, 'tipo', t.tipo, 'data', t.data, 'situacao', t.situacao, 'descricao', t.descricao,
    'concluida_em', t.concluida_em,
    'numero_os', coalesce(nullif(btrim(os.numero_os), ''), os.os_num::text, os.id::text),
    'cliente_nome', coalesce(nullif(btrim(os.cliente_nome), ''), 'Cliente não informado')
  )
    into v_linha
  from public.tarefas as t
  join public.ordens_servico as os on os.id = t.os_id
  where t.id = v_tarefa.id;

  v_resultado := jsonb_build_object('sucesso', true, 'repetido', v_ja_concluida, 'tarefa', v_linha, 'avisos', '[]'::jsonb);

  if p_chave is not null and not v_ja_concluida then
    insert into public.tarefas_operacoes (chave, tenant_id, operacao, tarefa_id, resultado)
    values (p_chave, v_sessao.tenant_id, 'tablet_concluir', v_tarefa.id, v_resultado)
    on conflict (chave) do nothing;
  end if;

  return v_resultado;
end;
$function$;

-- 5. Grants ----------------------------------------------------------------------------

revoke all on function public.fn_tarefas_erro(text, text) from public, anon, authenticated;
revoke all on function public.fn_tarefas_nome_usuario(uuid) from public, anon, authenticated;
revoke all on function public.fn_tarefas_contexto() from public, anon, authenticated;
revoke all on function public.fn_tarefas_linhas(uuid, uuid, uuid, boolean, uuid) from public, anon, authenticated;
revoke all on function public.fn_tarefas_linha_json(uuid, uuid, uuid, uuid, boolean, uuid) from public, anon, authenticated;
revoke all on function public.fn_tarefas_conflito(uuid, uuid, uuid, uuid, date, uuid, uuid, boolean, uuid) from public, anon, authenticated;
revoke all on function public.fn_tarefas_reservar(public.tarefas, uuid, date, uuid, boolean, uuid) from public, anon, authenticated;
revoke all on function public.fn_tarefas_liberar(uuid, uuid, text) from public, anon, authenticated;
revoke all on function public.fn_tarefas_travar(uuid, uuid, uuid) from public, anon, authenticated;
revoke all on function public.fn_tarefas_pode_gerir_os(integer, uuid, boolean) from public, anon, authenticated;

revoke all on function public.app_tarefas_contexto() from public, anon;
revoke all on function public.app_tarefas_criar(text, uuid, integer, text, date, uuid) from public, anon;
revoke all on function public.app_tarefas_alterar(uuid, text) from public, anon;
revoke all on function public.app_tarefas_reagendar(uuid, date) from public, anon;
revoke all on function public.app_tarefas_trocar_colaborador(uuid, uuid) from public, anon;
revoke all on function public.app_tarefas_cancelar(uuid, text) from public, anon;
revoke all on function public.app_tarefas_concluir(uuid, uuid) from public, anon;
revoke all on function public.app_tarefas_liberar_reserva(uuid, text) from public, anon;
revoke all on function public.app_tarefas_listar(text, date, date, uuid, integer, text) from public, anon;
revoke all on function public.app_tarefas_detalhe(uuid) from public, anon;
revoke all on function public.app_tarefas_contar() from public, anon;
revoke all on function public.app_tarefas_agenda(date, date) from public, anon;
revoke all on function public.app_tarefas_colaboradores(date) from public, anon;
revoke all on function public.app_tarefas_os_elegiveis(text) from public, anon;
revoke all on function public.app_tablet_tarefas(text) from public, anon;
revoke all on function public.app_tablet_tarefa_concluir(text, uuid, uuid) from public, anon;

grant execute on function public.app_tarefas_contexto() to authenticated;
grant execute on function public.app_tarefas_criar(text, uuid, integer, text, date, uuid) to authenticated;
grant execute on function public.app_tarefas_alterar(uuid, text) to authenticated;
grant execute on function public.app_tarefas_reagendar(uuid, date) to authenticated;
grant execute on function public.app_tarefas_trocar_colaborador(uuid, uuid) to authenticated;
grant execute on function public.app_tarefas_cancelar(uuid, text) to authenticated;
grant execute on function public.app_tarefas_concluir(uuid, uuid) to authenticated;
grant execute on function public.app_tarefas_liberar_reserva(uuid, text) to authenticated;
grant execute on function public.app_tarefas_listar(text, date, date, uuid, integer, text) to authenticated;
grant execute on function public.app_tarefas_detalhe(uuid) to authenticated;
grant execute on function public.app_tarefas_contar() to authenticated;
grant execute on function public.app_tarefas_agenda(date, date) to authenticated;
grant execute on function public.app_tarefas_colaboradores(date) to authenticated;
grant execute on function public.app_tarefas_os_elegiveis(text) to authenticated;
grant execute on function public.app_tablet_tarefas(text) to authenticated;
grant execute on function public.app_tablet_tarefa_concluir(text, uuid, uuid) to authenticated;

-- 6. Conferencia ------------------------------------------------------------------------

do $assertions$
declare
  v_acl text;
  v_nome text;
begin
  foreach v_nome in array array['tarefas', 'tarefas_reservas', 'tarefas_operacoes'] loop
    if not exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and c.relname = v_nome and c.relrowsecurity) then
      raise exception 'rls_desligada: %', v_nome;
    end if;
    if exists (select 1 from pg_policies where schemaname = 'public' and tablename = v_nome) then
      raise exception 'policy_inesperada: %', v_nome;
    end if;
    if has_table_privilege('authenticated', format('public.%I', v_nome), 'select') then
      raise exception 'tabela_aberta_para_authenticated: %', v_nome;
    end if;
  end loop;

  foreach v_nome in array array['uq_tarefas_reservas__colaborador_dia', 'uq_tarefas_reservas__usuario_dia', 'uq_tarefas_reservas__tarefa_ativa'] loop
    if not exists (select 1 from pg_indexes where schemaname = 'public' and indexname = v_nome and indexdef ilike 'create unique index%') then
      raise exception 'indice_unico_ausente: %', v_nome;
    end if;
  end loop;

  if not exists (select 1 from pg_trigger where tgname = 'trg_tarefas_audit' and tgrelid = 'public.tarefas'::regclass)
     or not exists (select 1 from pg_trigger where tgname = 'trg_tarefas_reservas_audit' and tgrelid = 'public.tarefas_reservas'::regclass) then
    raise exception 'auditoria_ausente';
  end if;

  for v_acl in
    select coalesce(p.proacl::text, '')
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and (p.proname like 'app\_tarefas\_%' or p.proname like 'fn\_tarefas\_%' or p.proname like 'app\_tablet\_tarefa%')
  loop
    if v_acl like '%anon=%' or v_acl like '{=X%' then
      raise exception 'grant_tarefas_aberto: %', v_acl;
    end if;
  end loop;

  for v_acl in
    select p.proname::text
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname like 'fn\_tarefas\_%'
      and has_function_privilege('authenticated', p.oid, 'execute')
  loop
    raise exception 'helper_exposto: %', v_acl;
  end loop;
end;
$assertions$;

notify pgrst, 'reload schema';

commit;
