-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20260211_fornecedores_gerar_contas_pagar_auto.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
