begin;

-- Trilha imutavel das propostas confirmadas pelo cadastro assistido por IA.
-- A escrita e feita exclusivamente pelo backend com a service role; usuarios
-- autenticados podem somente consultar registros do proprio tenant/empresa.
create table if not exists public.item_cadastro_agente_sugestoes (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  empresa_id uuid not null,
  item_id integer not null,
  fornecedor_id integer not null,
  codigo_interno text not null,
  quantidade_referencia numeric(14,3) not null,
  sugestao_json jsonb not null default '{}'::jsonb,
  pesquisa_precos_json jsonb not null default '[]'::jsonb,
  preco_origem numeric(14,4),
  preco_final numeric(14,4),
  moeda_origem varchar(3),
  regra_preco text,
  multiplicador_preco numeric(8,4) not null default 1,
  item_similar_id integer,
  fiscal_sugerido_json jsonb not null default '{}'::jsonb,
  modelo text not null,
  confirmado_por text not null,
  confirmado_em timestamp with time zone not null default now(),
  criado_em timestamp with time zone not null default now(),
  constraint item_cadastro_agente_sugestoes_codigo_nao_vazio_ck
    check (btrim(codigo_interno) <> ''),
  constraint item_cadastro_agente_sugestoes_quantidade_positiva_ck
    check (quantidade_referencia > 0),
  constraint item_cadastro_agente_sugestoes_sugestao_json_obj_ck
    check (jsonb_typeof(sugestao_json) = 'object'),
  constraint item_cadastro_agente_sugestoes_pesquisa_precos_json_arr_ck
    check (jsonb_typeof(pesquisa_precos_json) = 'array'),
  constraint item_cadastro_agente_sugestoes_fiscal_json_obj_ck
    check (jsonb_typeof(fiscal_sugerido_json) = 'object'),
  constraint item_cadastro_agente_sugestoes_preco_origem_positivo_ck
    check (preco_origem is null or preco_origem >= 0),
  constraint item_cadastro_agente_sugestoes_preco_final_positivo_ck
    check (preco_final is null or preco_final >= 0),
  constraint item_cadastro_agente_sugestoes_moeda_formato_ck
    check (
      moeda_origem is null
      or (moeda_origem = upper(moeda_origem) and moeda_origem ~ '^[A-Z]{3}$')
    ),
  constraint item_cadastro_agente_sugestoes_multiplicador_positivo_ck
    check (multiplicador_preco > 0),
  constraint item_cadastro_agente_sugestoes_modelo_nao_vazio_ck
    check (btrim(modelo) <> ''),
  constraint item_cadastro_agente_sugestoes_confirmado_por_nao_vazio_ck
    check (btrim(confirmado_por) <> ''),
  constraint item_cadastro_agente_sugestoes_item_escopo_fk
    foreign key (tenant_id, empresa_id, item_id)
    references public.itens (tenant_id, empresa_id, id)
    on delete restrict,
  constraint item_cadastro_agente_sugestoes_fornecedor_escopo_fk
    foreign key (tenant_id, empresa_id, fornecedor_id)
    references public.fornecedores (tenant_id, empresa_id, id)
    on delete restrict,
  constraint item_cadastro_agente_sugestoes_item_similar_escopo_fk
    foreign key (tenant_id, empresa_id, item_similar_id)
    references public.itens (tenant_id, empresa_id, id)
    on delete restrict
);

create index if not exists idx_item_cadastro_agente_sugestoes_item
  on public.item_cadastro_agente_sugestoes (
    tenant_id,
    empresa_id,
    item_id,
    confirmado_em desc
  );

create index if not exists idx_item_cadastro_agente_sugestoes_fornecedor_codigo
  on public.item_cadastro_agente_sugestoes (
    tenant_id,
    empresa_id,
    fornecedor_id,
    codigo_interno,
    confirmado_em desc
  );

create index if not exists idx_item_cadastro_agente_sugestoes_item_similar
  on public.item_cadastro_agente_sugestoes (
    tenant_id,
    empresa_id,
    item_similar_id
  )
  where item_similar_id is not null;

alter table public.item_cadastro_agente_sugestoes enable row level security;

drop policy if exists item_cadastro_agente_sugestoes_select
  on public.item_cadastro_agente_sugestoes;
create policy item_cadastro_agente_sugestoes_select
  on public.item_cadastro_agente_sugestoes
  for select to authenticated
  using (
    tenant_id = public.current_tenant_id()
    and empresa_id = public.current_empresa_id()
    and (
      public.can('cad_itens', 'write')
      or public.can('estoque', 'write')
    )
  );

-- Nao ha policies de insert/update/delete. A tabela e uma auditoria imutavel
-- gravada pelo servidor apos a confirmacao humana do cadastro.
revoke all on table public.item_cadastro_agente_sugestoes from authenticated;
grant select on table public.item_cadastro_agente_sugestoes to authenticated;
grant all on table public.item_cadastro_agente_sugestoes to service_role;
grant usage, select on sequence public.item_cadastro_agente_sugestoes_id_seq to service_role;

comment on table public.item_cadastro_agente_sugestoes is
  'Auditoria imutavel de propostas de cadastro de item confirmadas pelo agente de IA, incluindo fontes de preco e referencia fiscal interna.';
comment on column public.item_cadastro_agente_sugestoes.quantidade_referencia is
  'Quantidade informada somente para cotacao. Nao cria nem movimenta estoque.';
comment on column public.item_cadastro_agente_sugestoes.sugestao_json is
  'Proposta completa aprovada, incluindo descricao normalizada, grupo e dados comerciais revisados.';
comment on column public.item_cadastro_agente_sugestoes.pesquisa_precos_json is
  'Fontes externas consultadas pelo agente, com URL, marketplace, preco, moeda e tipo de correspondencia.';
comment on column public.item_cadastro_agente_sugestoes.item_similar_id is
  'Item interno usado como referencia para a sugestao fiscal/comercial, quando houver.';

commit;
