-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20260128_fix_gerar_ap_pendente_por_nf_entrada_v2.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
