-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20260306103000_fix_compra_varredura_cancelar_pendente_coberta_por_em_pedido.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
