-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20260201_fix_add_os_item_baixa_imediata.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
