-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20260217_fix_has_permission_undefined.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
