-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20260221170000_fix_compra_pendencia_trigger_sem_pedido_item_deleted_at.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
