-- Marcador historico: esta versao ja foi aplicada em producao.
-- O SQL original permanece em supabase/migrations/_arquivo/20260209_fix_rpc_overloads_and_seed_os_gestao_itens.sql.
-- O efeito acumulado desta versao ja integra 00000000000000_baseline_producao.sql.
