export type OrcamentoStatus = "ANDAMENTO" | "FECHADO" | "PERDIDO" | "RASCUNHO" | "FINALIZADO" | "CANCELADO";

export type OrcamentoListaRow = {
  id: string;
  codigo: string;
  numero: number;
  versao: number;
  status: OrcamentoStatus | string;
  emissao_date: string;
  titulo: string;
  cliente_id: number;
  cliente_nome: string | null;
  vendedor_usuario_id: string;
  vendedor_nome: string | null;
  condicao_pagamento_id: string | null;
  condicao_pagamento_nome: string | null;
  desconto_global_percent: number | string | null;
  acrescimo_cond_pag_percent: number | string | null;
  valor_frete: number | string | null;
  total_produtos: number | string | null;
  total_servicos: number | string | null;
  total_bruto: number | string | null;
  total_desconto_global: number | string | null;
  total_liquido: number | string | null;
  valor_fechado: number | string | null;
  desconto_fechamento_valor: number | string | null;
  desconto_fechamento_percent: number | string | null;
  observacoes: string | null;
  os_id: number | null;
  os_itens_importados_at: string | null;
  created_at: string;
  updated_at: string;
};

export type OrcamentoAnaliticoRow = {
  id: string;
  codigo: string;
  titulo: string;
  status: OrcamentoStatus | string;
  emissao_date: string;
  cliente_id: number | null;
  cliente_nome: string | null;
  vendedor_usuario_id: string | null;
  vendedor_nome: string | null;
  total_liquido: number | string | null;
  valor_fechado: number | string | null;
  desconto_fechamento_valor: number | string | null;
  desconto_fechamento_percent: number | string | null;
  updated_at: string;
};

export type OrcamentoRow = {
  id: string;
  tenant_id: string;
  empresa_id: string;
  numero: number;
  versao: number;
  codigo: string;
  status: OrcamentoStatus | string;
  emissao_date: string;
  titulo: string;
  cliente_id: number;
  vendedor_usuario_id: string;
  condicao_pagamento_id: string | null;
  acrescimo_cond_pag_percent: number | string;
  desconto_global_percent: number | string;
  valor_frete: number | string;
  total_produtos: number | string;
  total_servicos: number | string;
  total_bruto: number | string;
  total_desconto_global: number | string;
  total_liquido: number | string;
  valor_fechado: number | string | null;
  solicitante_nome: string | null;
  solicitante_setor: string | null;
  solicitante_email: string | null;
  solicitante_telefone: string | null;
  drive_folder_id: string | null;
  drive_folder_url: string | null;
  drive_doc_id: string | null;
  drive_doc_url: string | null;
  drive_sync_status: string | null;
  drive_sync_error: string | null;
  drive_sync_requested_at: string | null;
  drive_synced_at: string | null;
  prazo_entrega: string | null;
  garantia: string | null;
  validade_proposta: string | null;
  observacoes: string | null;
  os_id: number | null;
  os_itens_importados_at: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
};

export type OrcamentoItemRow = {
  id: string;
  orcamento_id: string;
  seq: number;
  item_id: number;
  item_codigo_interno?: string | null;
  observacoes?: string | null;
  item_tipo: "PRODUTO" | "SERVICO" | string;
  item_nome: string;
  unidade: string;
  quantidade: number | string;
  valor_unitario: number | string;
  desconto_item_percent: number | string;
  acrescimo_cond_pag_percent: number | string;
  desconto_global_percent: number | string;
  valor_total_bruto: number | string;
  valor_total: number | string;
  valor_unitario_liquido: number | string;
  created_at: string;
  updated_at: string;
};

export type ConfigOrcamentoRow = {
  id: string;
  tenant_id: string;
  empresa_id: string;
  margem_lucro_padrao_percent: number | string;
  desconto_max_percent: number | string;
  condicao_pagamento_padrao_id: string | null;
  conjunto_categorias: string[] | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
};

export type CondicaoPagamentoRow = {
  id: string;
  tenant_id: string;
  empresa_id: string;
  codigo: string;
  nome: string;
  acrescimo_percent: number | string;
  dias: number | null;
  ativo: boolean;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
};

export type ClienteLookupRow = { id: number; nome: string | null; documento: string | null };
export type ClienteContatoLookupRow = {
  id: number | string;
  nome: string | null;
  setor: string | null;
  email: string | null;
  telefone: string | null;
  principal: boolean | null;
  vezes_usado: number | string | null;
  ultimo_uso_em: string | null;
};
export type UsuarioLookupRow = { id: string; nome: string | null };
export type ItemLookupRow = {
  id: number;
  nome: string | null;
  tipo: string | null;
  unidade_medida: string | null;
  preco_unitario: number | string | null;
  ativo: boolean | null;
};
